#!/usr/bin/python

import sys
import os
import re

try:
    os.system('bcompare "%s" "%s"' % (sys.argv[2], sys.argv[5]))
except:
    print (str(sys.argv[0]) + ': error!')
    print ('Do you have the program "bcompare" installed in your system?')
    exit(1)

