#!/bin/bash

global_num=0

# print_line [branch_colored] [path]
function print_line {
	printf "%3d " $global_num
	echo -en "$1"
	for i in $(seq 1 $((34 - ${#1}))); do
		echo -n " "
	done
	echo -e "$2"
}

# dir_iterate [dir_path]
function dir_iterate {
	for d in "$1"/*; do
		dir_array[$i]=$d
		((i++))
		if [ -d "$d" ]; then
			if [ -d "$d"/.git ]; then
				pushd "$d" > /dev/null
				branch=`git branch | grep \* | awk '{print $2}'`
				git update-index -q --refresh
				git diff-index --quiet HEAD --
				((global_num++))
				if [ 0 -eq $? ]; then
					print_line "{\e[1;32m$branch\e[0m}" "$d"
				else
					print_line "{\e[1;31m$branch\e[0m}" "$d"
				fi
				popd > /dev/null
			else
				dir_iterate "$d"
			fi
		fi
	done
}

function _main {
	dir_iterate `pwd`
	return 0
}

_main
exit $?
